import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import {
  XYPlot,
  XAxis,
  YAxis,
  HorizontalGridLines,
  LineSeries,
} from "react-vis";
import Navbar from "../components/Navbar";
import { Button, Container, Form, FormControl, Row } from "react-bootstrap";

export async function getStaticProps() {
  const stocks = await fetch("http://localhost:5000/stocks").then((res) =>
    res.json()
  );
  return {
    props: { stocks }, // will be passed to the page component as props
  };
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container className="glass mt-5">
        <div className="d-flex w-100 h-100 flex-column justify-content-center align-items-center">
          <h1>PyStonks</h1>
          <h2>Enter a stock to get started</h2>
          <Form className="mt-5 w-50">
              <FormControl
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <Button className="w-100 mt-1">Search</Button>
          </Form>
          </div>
      </Container>
    </div>
  );
}
